# Generated by Django 3.2.2 on 2022-10-20 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
                ('value', models.CharField(default='', max_length=60)),
                ('descripcion', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'db_table': 'configuracion',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'equipo',
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, default='', max_length=60)),
                ('cerrado', models.BooleanField(blank=True, default=False)),
                ('resultado_equipo_1', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('resultado_equipo_2', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('terminado', models.BooleanField(blank=True, default=False)),
                ('equipo_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo1_set', to='apuestas.equipo')),
                ('equipo_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipo2_set', to='apuestas.equipo')),
            ],
            options={
                'db_table': 'partido',
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=60)),
            ],
            options={
                'db_table': 'torneo',
            },
        ),
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pronostico_equipo_1', models.PositiveIntegerField()),
                ('pronostico_equipo_2', models.PositiveIntegerField()),
                ('puntaje', models.PositiveIntegerField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuestas.partido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pronostico',
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apuestas.torneo'),
        ),
    ]
